### PR TITLE
Bm fix q13

### PR DESCRIPTION
**Pull request by q10**

### CODE REVIEW

**Comment by q10** [comment]
Note that while the query generation for ILIKE seems to work now, Q13 still has not quite passed.  The test ouput detailing the results mismatch is as follows:

```
List((1,50022), (2,134), (3,415), (4,1007), (5,1948), (6,3265), (7,4687), (8,5937), (9,6641), (10,6532), (11,6014), (12,5639), (13,5024), (14,4446), (15,4505), (16,4273), (17,4587), (18,4529), (19,4793), (20,4516), (21,4190), (22,3623), (23,3225), (24,2742), (25,2086), (26,1612), (27,1179), (28,893), (29,593), (30,376), (31,226), (32,148), (33,75), (34,50), (35,37), (36,14), (37,5), (38,5), (39,1), (40,4), (41,2)) 

did not equal 

List((0,50005), (1,17), (2,134), (3,415), (4,1007), (5,1948), (6,3265), (7,4687), (8,5937), (9,6641), (10,6532), (11,6014), (12,5639), (13,5024), (14,4446), (15,4505), (16,4273), (17,4587), (18,4529), (19,4793), (20,4516), (21,4190), (22,3623), (23,3225), (24,2742), (25,2086), (26,1612), (27,1179), (28,893), (29,593), (30,376), (31,226), (32,148), (33,75), (34,50), (35,37), (36,14), (37,5), (38,5), (39,1), (40,4), (41,2))
```

Notice how the first tuple in the results list is an element-wise sum of the first two tuples in the expected list.  I am not sure how this came to be (might be due to an older version of frovedis?), but other than this discrepancy, the code generation itself looks alright.

**Comment by wgip** [comment]
@q10 can you check if the matching in the grouping is done wrongly somehow. It seems the key for 0 and 1 is flattened into 1. IIRC it is done fine but might not be

**Comment by q10** [comment]
I looked through the generated code and could not find anything suspicious from this generated snippet (cleaned):

```
  std::vector<int> slowStringEvaluation_1752250258(input_8->count);
  for ( int i = 0; i < input_8->count; i++) { 
    slowStringEvaluation_1752250258[i] = check_valid(input_8->validityBuffer, i);
  }

  std::vector<int> output_823000408(input_8->count);
  frovedis::words input_words_823000408 = varchar_vector_to_words(input_8);
  std::vector<size_t> matching_ids_823000408 = frovedis::like(input_words_823000408, "%special%requests%");

  for ( int i = 0; i < input_8->count; i++ ) {
    output_823000408[i] = 0;
  }
  for ( int i = 0; i < matching_ids_823000408.size(); i++ ) {
    output_823000408[matching_ids_823000408[i]] = 1;
  }
  std::vector<size_t> matching_ids;
  for ( int i = 0; i < input_0->count; i++ ) {
    if (((slowStringEvaluation_1752250258[i]) && (!(output_823000408[i])))) { 
      matching_ids.push_back(i);
    }
  }
```

The rest of the generated code only deals with copying the results over to the `output`s.

**Comment by q10** [comment]
Since the workflows have been redefined, ran the unit tests locally:
image

**Review by wmeddie — APPROVED** [review]
The problem for q13 definitely stems from eg_remove_imp_str and not this fix.

**Pull request merged**
