### PR TITLE
Remove usage of allocateDirect, prefer a new BytePointer instead (wil…

### PR DESCRIPTION
**Pull request by EmergentOrder**
…l replace ByteBuffer usage); Remove now redundant little endian order calls

### CODE REVIEW

**Comment by Wosin** [comment]
Seems that something is not ok, 21 tests failed with`TPC (VE)` run, we usually had around 9/10 failures.

**Comment by EmergentOrder** [comment]
Ahh I had only run sbt test and query 1, will be sure to run all locally.
It looks like some of the new'ed BytePointers are triggering NPEs, not sure why.
Reverted just those and running all queries locally now.

**Comment by EmergentOrder** [comment]
OK, looks better now, 9 test failures on the queries.
Will look at removing those last few allocateDirect calls without NPE in the next PR.

**Comment by EmergentOrder** [comment]
Tried re-running the action, but it doesn't look like it picked up the second commit

**Comment by EmergentOrder** [comment]
This is ready to merge.

**Review by wmeddie — APPROVED** [review]
No issues encountered.

**Pull request merged**
