### PR TITLE
change malloc to calloc in validityBuffer allocations

### PR DESCRIPTION
**Pull request by BrainyGuyOrg**
also clean up int->float->int allocation expression

### CODE REVIEW

**Comment by BrainyGuyOrg** [comment]
Ran Query 2 (1SF) and CMake / test.

**Comment by wgip** [comment]
Just curious, could this be extracted into some form of C++ template? I am not familiar hence asking.

**Review by q10 — APPROVED** [review]
LGTM

**Comment by BrainyGuyOrg** [comment]
> Just curious, could this be extracted into some form of C++ template? I am not familiar hence asking.

Maybe not a template, but I suppose it could be pulled into a separate function. It is just one line, so even a function feels like overkill. But I understand your sentiment.

**Pull request merged**
