### PR TITLE
Restructure the `src/main/resources/com/nec/cyclone/cpp` directory

### PR DESCRIPTION
**Pull request by q10**
As part of extracting generated C++ code into common library functions, some work is first needed to make the `cpp/` directory work as if it were a full project on its own. 

Summary:

1. Move the existing cyclone-specific code (`cyclone.hpp` and `transfer-definitinos.hpp`) into the cyclone/ subdirectory.
2. Deleted `utility.hpp`, which is a copy of `frovedis/core/utility.hpp`
3. Added the `doctest` C++ unit testing framework.  This framework is chosen because it compiles and runs fast, it is a single-header library, and it is MIT-licensed so should not have licensing conflicts with SparkCyclone.
4. Add an example library function implementation along with unit tests
5. Rewrite the Makefile so that it can build and run tests and example code on both Linux and Mac machines
6. Update `build.sbt` so that unit tests are run whenever `libcyclone.so` is to be (re-)built.  This hooks up the C++ library development to the sbt developement cycle.
7. Update the C++ code generation with the new header paths for `cyclone.hpp` and `transfer-definitions.hpp`
8. Removed unnecessary `#include`s from cyclone library code, which may help with faster builds
9. Add a README to onboard developers to Cyclone C++ library development

When bad C++ is introduced to the library in the form of failing tests, the failing test will bubble up to sbt: 

image

Likewise, if all tests pass, then TPCH query can be run:

image

### CODE REVIEW

**Review by wgip — APPROVED** [review]

**Comment by wgip** [comment]
Great PR summary, especially the reasoning behind the changes.

Didn't get a chance to test drive it yet but lgtm.

**Comment by wgip** [comment]
(Do check CMake scope tests they seem to be failing)

**Comment by q10** [comment]
Q7, 8, 9 were failing due to missing headers that were not transitively `#include`d anymore through `cyclone.hpp`.  Pushed change, running tests again to verify.

**Comment by q10** [comment]
It looks like CMake tests are failing because the version of `gcc` on the machine is 4.8, and `gcc` 7+ is required for full C++17 features, including nested namespaces (see [here](https://gcc.gnu.org/projects/cxx-status.html)).

**Comment by wgip** [comment]
@q10 gcc 11 is now on a6 and vh001

`yum install -y devtoolset-11-gcc-c++-11.2.1-1.2.el7.x86_64`

enable with `source /opt/rh/devtoolset-11/enable`

best to integrate into the gh action job.

giving errors different from namespace ones

image

**Comment by q10** [comment]
Some fixes have been put in place to allow the generated code in Unit tests (CMake) to compile without `#include` problems; however, bc CMake is globbing up doctest-related code when it builds the test library.  This appears to be causing runtime exceptions when the `libsparkcyclone.so` (not the same as `libcyclone.so` which is generated in production) is linked and run, and the JVM crashes after a certain point during running the CMake tests.  I don't think this is a problem with production code, since the full TPC benchmarks have been running properly.  @wmeddie is working on a fix to the CMakeBuilder class to glob files more selectively.

**Review by wgip — CHANGES_REQUESTED** [review]
Can you remove/not include the `doctest.h` and `tests` into the copied target? (as you mention the CMake is picking everything up?)

if we're not going to support the `CMake` scope properly any more we might as well move to `ncc` fully so it's at least consistent (while local-dev is really beneficial). WDYT?

**Comment by q10** [comment]
> Can you remove/not include the `doctest.h` and `tests` into the copied target? (as you mention the CMake is picking everything up?)
> 
> if we're not going to support the `CMake` scope properly any more we might as well move to `ncc` fully so it's at least consistent (while local-dev is really beneficial). WDYT?

Yep, this is now not copied over thanks to https://github.com/XpressAI/SparkCyclone/pull/486.  I have rebased the PR on the latest `main` to pick up the fix.

**Comment by q10** [comment]
The TPC VE failed on almost all tests for some reason, but a [subsequent run](https://github.com/XpressAI/SparkCyclone/runs/5103054317?check_suite_focus=true) fully passes

**Pull request merged**
