### PR TITLE
Remove ImperativeString* Implementations.

### PR DESCRIPTION
**Pull request by wmeddie**
Using Frovedis data structures instead of std::string provides a
significant performance boost.

A similar PR exists that does this plus, changes our varchar data structure. This should be merged first instead.

### CODE REVIEW

**Comment by wgip** [comment]
running tpc-h central now

**Comment by wgip** [comment]
@wmeddie  q10 & q12 
image

**Comment by wmeddie** [comment]
Ah. I had that fixed in the original branch. Let me fix it.

**Comment by wgip** [comment]
Synchronized, and ran all the tests. This one stood out in particular though and it seems could be related to the String functionality.



```
[info] ArrowTransferCheck:
[info] Identify check: data that we put into the VE can be retrieved back out
[info] - for Float8Vector
[info] - for VarCharVector
[info] - for BigInt
[info] - for Int
[info] - Execute our function
[info] - Execute multi-function
[info] - Partition data by some means (simple Int partitioning in this case) (PIN) *** FAILED ***
[info]   Set((1.0,a,9.0), (2.0,b,8.0), (3.0,,7.0)) did not equal Set((1.0,a,9.0), (2.0,b,8.0), (3.0,cccc,7.0)) we verify that we get back the data we had put in (ArrowTransferCheck.scala:189)
[info]   Analysis:
[info]   Set(missingInLeft: [(3.0,cccc,7.0)], missingInRight: [(3.0,,7.0)])
```

**Pull request merged**
