### PR TITLE
[tpch-q19] Fix code generation for IN string queries

### PR DESCRIPTION
**Pull request by q10**
- Add scope to the C++ code generation for IN string queries to avoid
name clashing when compiling the gnerated code

### CODE REVIEW

**Comment by q10** [comment]
The generated C++ snippet looks as follows:

```
  std::vector<size_t> filtered_ids_1445657502(input_6->count);
  {
    // STEP: Filter input_6 to values of the given set
    frovedis::words input_words_1445657502 = varchar_vector_to_words(input_6);
    std::vector<int> values_1445657502 { 76,71,32,67,65,83,69,32,76,71,32,66,79,88,32,76,71,32,80,65,67,75,32,76,71,32,80,75,71 };
    frovedis::words filtering_set_1445657502 = frovedis::split_to_words(values_1445657502, " ");
    auto NOT_FOUND = std::numeric_limits<size_t>::max();
    std::vector<size_t> matching_ids_1445657502 = filter_words_dict(input_words_1445657502, filtering_set_1445657502);
    for ( int i = 0; i < matching_ids_1445657502.size(); i++ ) {
      if (matching_ids_1445657502[i] != NOT_FOUND) { 
        filtered_ids_1445657502[i] = 1;
      } else {
        filtered_ids_1445657502[i] = 0;
      }
    }
  }
```

`filtered_ids_*` remains outside of the block as it is used by subsequent steps in the code

**Comment by q10** [comment]
Though the query code is correctly generated now without name clashes, it is still failing:

```
[info] TPCHVESqlSpec:
[info] - Query 19 *** FAILED ***
[info]   List() did not equal List(3083843.057799999) (TPCHSqlCSpec.scala:1296)
[info]   Analysis:
[info]   Nil$(0: -> 3083843.057799999)
```

This appears to be similar to the issue with Q21

**Comment by wgip** [comment]
@q10 could also suffix/prefix the `NOT_FOUND` so it's always unique.
Not sure about why it's failing functionally though. Might be worth to investigate, eg check the TPCJVMSqlSpec

**Comment by q10** [comment]
Updated to make the `NOT_FOUND` variable unique.

The generated physical plan when running TPCHSqlSpecJVM is:

```
== Physical Plan ==
*(6) HashAggregate(keys=[], functions=[sum((l_extendedprice#56 * (1.0 - l_discount#57)))], output=[revenue#1947])
+- Exchange SinglePartition, ENSURE_REQUIREMENTS, [id=#340]
   +- *(5) HashAggregate(keys=[], functions=[partial_sum((l_extendedprice#56 * (1.0 - l_discount#57)))], output=[sum#2326])
      +- *(5) Project [l_extendedprice#56, l_discount#57]
         +- *(5) SortMergeJoin [l_partkey#52L], [p_partkey#180L], Inner, (((((((p_brand#183 = Brand#12) AND p_container#186 IN (SM CASE,SM BOX,SM PACK,SM PKG)) AND (l_quantity#55 >= 1.0)) AND (l_quantity#55 <= 11.0)) AND (p_size#185L <= 5)) OR (((((p_brand#183 = Brand#23) AND p_container#186 IN (MED BAG,MED BOX,MED PKG,MED PACK)) AND (l_quantity#55 >= 10.0)) AND (l_quantity#55 <= 20.0)) AND (p_size#185L <= 10))) OR (((((p_brand#183 = Brand#34) AND p_container#186 IN (LG CASE,LG BOX,LG PACK,LG PKG)) AND (l_quantity#55 >= 20.0)) AND (l_quantity#55 <= 30.0)) AND (p_size#185L <= 15)))
            :- *(2) Sort [l_partkey#52L ASC NULLS FIRST], false, 0
            :  +- Exchange hashpartitioning(l_partkey#52L, 200), ENSURE_REQUIREMENTS, [id=#323]
            :     +- *(1) Project [l_partkey#52L, l_quantity#55, l_extendedprice#56, l_discount#57]
            :        +- *(1) Filter (((isnotnull(l_shipinstruct#64) AND l_shipmode#65 IN (AIR,AIR REG)) AND (l_shipinstruct#64 = DELIVER IN PERSON)) AND ((((l_quantity#55 >= 1.0) AND (l_quantity#55 <= 11.0)) OR ((l_quantity#55 >= 10.0) AND (l_quantity#55 <= 20.0))) OR ((l_quantity#55 >= 20.0) AND (l_quantity#55 <= 30.0))))
            :           +- Scan In-memory table lineitem [l_discount#57, l_extendedprice#56, l_partkey#52L, l_quantity#55, l_shipinstruct#64, l_shipmode#65], [isnotnull(l_shipinstruct#64), l_shipmode#65 IN (AIR,AIR REG), (l_shipinstruct#64 = DELIVER IN PERSON), ((((l_quantity#55 >= 1.0) AND (l_quantity#55 <= 11.0)) OR ((l_quantity#55 >= 10.0) AND (l_quantity#55 <= 20.0))) OR ((l_quantity#55 >= 20.0) AND (l_quantity#55 <= 30.0)))]
            :                 +- InMemoryRelation [l_orderkey#51L, l_partkey#52L, l_suppkey#53L, l_linenumber#54L, l_quantity#55, l_extendedprice#56, l_discount#57, l_tax#58, l_returnflag#59L, l_linestatus#60L, l_shipdate#61, l_commitdate#62, l_receiptdate#63, l_shipinstruct#64, l_shipmode#65, l_comment#66], StorageLevel(disk, memory, deserialized, 1 replicas)
            :                       +- *(1) SerializeFromObject [knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_orderkey AS l_orderkey#51L, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_partkey AS l_partkey#52L, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_suppkey AS l_suppkey#53L, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_linenumber AS l_linenumber#54L, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_quantity AS l_quantity#55, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_extendedprice AS l_extendedprice#56, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_discount AS l_discount#57, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_tax AS l_tax#58, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_returnflag AS l_returnflag#59L, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_linestatus AS l_linestatus#60L, staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, DateType, localDateToDays, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_shipdate, true, false) AS l_shipdate#61, staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, DateType, localDateToDays, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_commitdate, true, false) AS l_commitdate#62, staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, DateType, localDateToDays, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_receiptdate, true, false) AS l_receiptdate#63, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_shipinstruct, true, false) AS l_shipinstruct#64, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_shipmode, true, false) AS l_shipmode#65, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, com.nec.tpc.Lineitem, true])).l_comment, true, false) AS l_comment#66]
            :                          +- Scan[obj#50]
            +- *(4) Sort [p_partkey#180L ASC NULLS FIRST], false, 0
               +- Exchange hashpartitioning(p_partkey#180L, 200), ENSURE_REQUIREMENTS, [id=#331]
                  +- *(3) Filter ((p_size#185L >= 1) AND (((((p_brand#183 = Brand#12) AND p_container#186 IN (SM CASE,SM BOX,SM PACK,SM PKG)) AND (p_size#185L <= 5)) OR (((p_brand#183 = Brand#23) AND p_container#186 IN (MED BAG,MED BOX,MED PKG,MED PACK)) AND (p_size#185L <= 10))) OR (((p_brand#183 = Brand#34) AND p_container#186 IN (LG CASE,LG BOX,LG PACK,LG PKG)) AND (p_size#185L <= 15))))
                     +- Scan In-memory table part [p_partkey#180L, p_brand#183, p_size#185L, p_container#186], [(p_size#185L >= 1), (((((p_brand#183 = Brand#12) AND p_container#186 IN (SM CASE,SM BOX,SM PACK,SM PKG)) AND (p_size#185L <= 5)) OR (((p_brand#183 = Brand#23) AND p_container#186 IN (MED BAG,MED BOX,MED PKG,MED PACK)) AND (p_size#185L <= 10))) OR (((p_brand#183 = Brand#34) AND p_container#186 IN (LG CASE,LG BOX,LG PACK,LG PKG)) AND (p_size#185L <= 15)))]
                           +- InMemoryRelation [p_partkey#180L, p_name#181, p_mfgr#182, p_brand#183, p_type#184, p_size#185L, p_container#186, p_retailprice#187, p_comment#188], StorageLevel(disk, memory, deserialized, 1 replicas)
                                 +- *(1) SerializeFromObject [knownnotnull(assertnotnull(input[0, com.nec.tpc.Part, true])).p_partkey AS p_partkey#180L, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, com.nec.tpc.Part, true])).p_name, true, false) AS p_name#181, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, com.nec.tpc.Part, true])).p_mfgr, true, false) AS p_mfgr#182, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, com.nec.tpc.Part, true])).p_brand, true, false) AS p_brand#183, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, com.nec.tpc.Part, true])).p_type, true, false) AS p_type#184, knownnotnull(assertnotnull(input[0, com.nec.tpc.Part, true])).p_size AS p_size#185L, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, com.nec.tpc.Part, true])).p_container, true, false) AS p_container#186, knownnotnull(assertnotnull(input[0, com.nec.tpc.Part, true])).p_retailprice AS p_retailprice#187, staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, knownnotnull(assertnotnull(input[0, com.nec.tpc.Part, true])).p_comment, true, false) AS p_comment#188]
                                    +- Scan[obj#179]
```

**Comment by q10** [comment]
I created a simpler version of the query string used in Q19:

```
    val sql = s"""
      select
        sum(l_extendedprice * (1 - l_discount) ) as revenue
      from
        lineitem,
        part
      where (
        p_partkey = l_partkey
        and p_brand = '$brand1'
        and p_container in ( 'SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
        and l_quantity >= $quantity1
        and l_quantity <= $quantity1 + 10
        and p_size between 1 and 5
        and l_shipmode in ('AIR', 'AIR REG')
        and l_shipinstruct = 'DELIVER IN PERSON'
      )
    """
```

Without the `and p_container in ( 'SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')` subclause in the bracket, I get some results, but as soon as I put that subclause back in, the query fails.

I think it has something to do with the fact that the values in the IN clause have spaces in between (e.g. `SM CASE`), and the generated code created words using space as the delimiter.  In the Scala code, we concat the strings with a space:

```
val words = valueList.mkString(" ").map(_.toInt).mkString(",")
...
              s"std::vector<int> ${values} { ${words} };",
              s"""frovedis::words ${filteringSet} = frovedis::split_to_words(${values}, " ");""",
...

and the generated C++:

```
frovedis::words filtering_set_1445657502 = frovedis::split_to_words(values_1445657502, " ");
```

What delimiter character should we use instead? @wmeddie

**Comment by q10** [comment]
Yep, confirmed that if I use `&` as a temporary replacement for space, then the simpler query returns results:

```
List(SM BOX, SM BOX, SM BOX, SM BOX, SM BOX, SM CASE, SM CASE, SM CASE, SM CASE, SM CASE, SM PACK, SM PACK, SM PACK, SM PACK, SM PACK, SM PACK, SM PACK, SM PACK, SM PKG, SM PKG, SM PKG, SM PKG, SM PKG, SM PKG, SM PKG)
```

**Comment by q10** [comment]
And now the full query passes:

```
sbt:spark-cyclone-sql-plugin> TPC / testOnly *TPC*VE* -- -z "Query 19"
[info] compiling 1 Scala source to /home/bm/SparkCyclone/target/scala-2.12/test-classes ...
[info] TPCHVESqlSpec:
[info] - Query 19
[info] Run completed in 1 minute, 7 seconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 71 s (01:11), completed Jan 18, 2022 2:20:58 AM
sbt:spark-cyclone-sql-plugin> 
```

**Comment by q10** [comment]
image

**Comment by wmeddie** [comment]
Awesome.  Using an ASCII character that isn't in the IN is a good idea and doesn't give us any arbitrary limitations in nearly all cases.

**Comment by q10** [comment]
Updated the PR to pick the next available character that isn't in the IN set of strings as the delimiter.

**Comment by q10** [comment]
Updated with unit tests:

image

**Review by wmeddie — APPROVED** [review]
I think this is good to merge now.

**Review by wgip — APPROVED** [review]

**Pull request merged**
